<?php
$class = $block->hasCssClass() ? $block->getCssClass() : 'default';
$messages = $block->hasData('messages') ? $block->getData('messages') : 'Hello Word';
?>
<!-- <h1 class="<?= $class ?>" style="float:left;"><?= $messages; ?></h1> -->
<?php
/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$productCollection = $objectManager
    ->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

$collection = $productCollection->create()
            ->addAttributeToSelect('*')
            ->load(true,false);
            
foreach ($collection as $product){
    echo 'Name = '.$product->getName().'<br/>';
}*/

/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$block = $objectManager
    ->create('\Magento\Catalog\Block\Product\ListProduct');
$block->setCategoryId(25);
$_productCollection=$block->getLoadedProductCollection();

if(!$_productCollection->count()){
	?>
	<div class="note-msg">
	    <?php echo 'There are no products matching the selection.'; ?>
	</div>
<?php
} else{

		foreach ($_productCollection as $_product){
		echo $_product->getName()."<br/>";
		echo $_product->getImage()."<br/>";
		echo $_product->getProduct()."<br/>";
		echo $_product->getDescription()."<br/>";
		echo $_product->getProductUrl()."<br/>";
		echo $_product->getSKU()."<br/>";
		echo $_product->getPrice()."<br/>";
		echo $_product->getVisibility()."<br/>";
		echo $_product->getAttributeSetId()."<br/>";
		echo $_product->getCreatedAt()."<br/>";
		echo $_product->getUpdatedAt()."<br/>";
		echo $_product->getTypeId()."<br/>";
		echo $_product->getStatus()."<br/>";
		echo $_product->getCategoryId()."<br/>";
		echo $_product->getQty()."<br/>";

	}
}*/
?>

