<?php
/**
 * @category   Ambab
 * @package    Ambab_Exchange
 * @author     letsdevelophp@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Ambab\Exchange\Block;

/**
 * Exchange content block
 */
class Exchange extends \Magento\Framework\View\Element\Template
{
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context
    ) {
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Exchange Product'));
        
        return parent::_prepareLayout();
    }

    public function getPincodes()
    {
        $options[0] =  ['value' => '', 'label' => ''];
        $options[1] =  ['value' => '400067', 'label' => '400067'];
        $options[2] =  ['value' => '486111', 'label' => '486111'];
        return $options;
    }

    public function getBedsheetqty()
    {
        $options[0] =  ['value' => '', 'label' => ''];
        $options[1] =  ['value' => '1', 'label' => '1'];
        $options[2] =  ['value' => '2', 'label' => '2'];
        $options[3] =  ['value' => '3', 'label' => '3'];
        return $options;
    }

    public function getPickupTimeLine()
    {
        $options[0] =  ['value' => '', 'label' => ''];
        $options[1] =  ['value' => 'Within the 7-14 days', 'label' => 'Within the 7-14 days'];
        $options[2] =  ['value' => 'After 2 weeks', 'label' => 'After 2 weeks'];
        $options[3] =  ['value' => 'Next month', 'label' => 'Next month'];
        return $options;
    }
    
}
