<style>
label.error {
  color:red;
}
</style>
<form action="<?php echo $block->getBaseUrl().'customerfeedback/index/index'; ?>" method="post" id="customerfeedbackform">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
    <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" id="customer_name" name="customer_name" placeholder="Enter Full Name">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="text" class="form-control" id="customer_email" name="customer_email" placeholder="Enter Full Email">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Phone no</label>
        <input type="text" class="form-control" id="customer_phone" name="customer_phone" placeholder="Enter Full Phone">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">subject</label>
        <input type="text" class="form-control" id="customer_subject" name="customer_subject" placeholder="Enter Subject">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Message</label>
        <input type="text" class="form-control" id="customer_Message" name="customer_message" placeholder="Enter Message">
    </div>
    <div class="form-group">
        <label for="sel1">Your Rating</label>
        <select class="form-control" id="feedback" name="rating">
            <option value="">Select Rating</option>
            <option value="Very good">Very good</option>
            <option value="Good">Good</option>
            <option value="Bad">Bad</option>
            <option value="Very Bad">Very Bad</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script type="text/javascript">
require(['jquery', 'jquery/ui', 'jquery/validate', 'Magento_Ui/js/modal/modal'], function ($, modal) {

     $('#customerfeedbackform').validate({
      rules: {
        customer_name: {
          required: true
        },
        customer_email: {
          required: true,
          email: true
        },
        customer_phone: {
          required: true,
          rangelength: [10, 12],
          number: true
        },
        customer_subject: {
          required: true,
          minlength: 8
        },
        customer_Message: {
          required: true,
        },
        rating: {
          required: true,
        }
      },
      messages: {
        customer_name: 'Please enter Name.',
        email: {
          required: 'Please enter Email Address.',
          email: 'Please enter a valid Email Address.',
        },
        customer_phone: {
          required: 'Please enter Contact.',
          rangelength: 'Contact should be 10 digit number.'
        }
      },
      submitHandler: function (form) {
        form.submit();
      }
    });
});
</script>