<style>
label.error {
color:red;
}
</style>
<form action="<?php echo $block->getBaseUrl().'customerfeedback/index/index'; ?>" method="post" id="customerfeedbackform" enctype="multipart/form-data">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Customer Feedback Form')) ?></span>
        </legend>
        <br>
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="customer_name" name="customer_name" placeholder="Enter Full Name">
            </div>
        </div>
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <input type="text" class="input-text" id="customer_email" name="customer_email" placeholder="Enter Full Email">
        </div>
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Phone No')) ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="customer_phone" name="customer_phone" placeholder="Enter Full Phone">
            </div>
        </div>
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Subject')) ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="customer_subject" name="customer_subject" placeholder="Enter Subject">
            </div>
        </div>
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="customer_Message" name="customer_message" placeholder="Enter Message">
            </div>
        </div>
        <div class="field">
            <label class="label"><span><?= $block->escapeHtml(__('Your Rating')) ?></span></label>
            <div class="control">
                <select class="select" id="feedback" name="rating">
                    <option value="">Select Rating</option>
                    <option value="Very good">Very good</option>
                    <option value="Good">Good</option>
                    <option value="Bad">Bad</option>
                    <option value="Very Bad">Very Bad</option>
                </select>
            </div>
        </div>
        <div class="field image">
            <label class="label" for="image"><span><?php /* @escapeNotVerified */ echo __('Image') ?></span></label>
            <div class="control">
                <input name="image" id="image" title="<?php /* @escapeNotVerified */ echo __('image') ?>" class="file"   type="file" />
                <img id="blah" style="display:none" src="#" alt="your image" />
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>
<script type="text/javascript">
require(['jquery', 'jquery/ui', 'jquery/validate', 'Magento_Ui/js/modal/modal'], function ($, modal) {
    $('#customerfeedbackform').validate({
        rules: {
            customer_name: {
                required: true
            },
            customer_email: {
                required: true,
                email: true
            },
            customer_phone: {
                required: true,
                rangelength: [10, 12],
                number: true
            },
            customer_subject: {
                required: true,
                minlength: 8
            },
            customer_Message: {
                required: true,
            },
            rating: {
                required: true,
            }
        },
        messages: {
            customer_name: 'Please enter Name.',
            email: {
                required: 'Please enter Email Address.',
                email: 'Please enter a valid Email Address.',
            },
            customer_phone: {
                required: 'Please enter Contact.',
                rangelength: 'Contact should be 10 digit number.'
            }
        },
        submitHandler: function (form) {
            form.submit();
        }
    });
    image.onchange = evt => {
        const [file] = image.files
        if (file) {
            $('#blah').show();
            blah.src = URL.createObjectURL(file)
        }
    }
});
</script>