<?php
$data = $block->getPincodeData();
?>
<form>
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name"placeholder="Enter name">
  </div>
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>