<?php
$data = $block->getPincodeData();
$url = $this->getUrl('pincodechecker');
echo $url;
?>
<form method="post" action="">
  <div class="form-group">
    <input type="text" class="form-control" id="pincode" name="pincode" placeholder="Enter pincode">
  </div>
  <button type="submit" class="btn btn-primary" id="submit">Submit</button>
  <span id="pincode-avail"></span>
</form>

<script type="text/javascript">
require(['jquery', 'Magento_Ui/js/modal/modal'], function ($, modal) {

     $(document).on('click','#submit', function(e){
        e.preventDefault();
          var pincode = $('#pincode').val();
          if(pincode == "")
          {
            alert("Please Enter Pincode");
            return false;
          }
          
          $.ajax({
            url: '<?php echo $url ?>',
            async:false,
            showLoader: true,
            type:'POST',
            data: {pincode:pincode},
            success: function(result){
                $('#pincode-avail').html(result);
            }
        });

    });

    $('#pincode').keypress(function(e){
        if(e.which == 13){
            e.preventDefault();
            $('#submit').click();
        }
    });
});
</script>