<script type="text/x-magento-init">
    { ".t-validate": { "Ambab_Exchange/js/custom_exchange": {} } }
</script>
<script src="https://www.google.com/recaptcha/api.js"></script>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base=$storeManager->getStore()->getBaseUrl();
?>

<div class="fluid--container">
  <div class="breadcrumbs-padding cart-block--progress">
    <ul class="breadcrumbs--wrap" itemscope itemtype="http://schema.org/BreadcrumbList">
      <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="breadcrumbs--name">
        <a itemprop="item" href="<?php echo $base ?>" class="breadcrumbs--link">
          <span itemprop="name">Home</span>
        </a>
        <meta itemprop="position" content="1" />
      </li>
      <li class="breadcrumbs--name" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
        <a itemprop="item" href="<?php echo $base ?>exchange-program">
          <span itemprop="name">Exchange Program</span>
        </a>
        <meta itemprop="position" content="2" />
      </li>
    </ul>
  </div>
</div>

<?php
    $pincode = $block->getPincodes();
    $bedsheetqty = $block->getBedsheetqty();
    $pickup = $block->getPickupTimeLine();
?>

<section class="responsive--container topbottom-margin">

  <h1 class="page--title icon text-left topbottom-margin"><i class="sp sp_bulk_order" path="17"></i>Exchange Program</h1>
  <div class="block--with-sidebar misc caterogy--listing-wrap">
    <div class="block--sidebar margin--b30">

<form class="white" action="<?php echo $block->getBaseUrl().'exchange/index/save'; ?>" id="ambab-exchange-form" method="post" data-mage-init='{"validation": {}}' onSubmit="return checkCaptcha() ;">

    <div class="form--input-field-wrap field name  required "> 
      <label class="pure-material-textfield-outlined" for="name">
         <input class="field- input-text t-validate" type="text" name="name" id="name" data-validate="{required:true}" placeholder="" aria-required="true">
         <span>Full Name*</span>
          </label>
   </div>

   <div class="form--input-field-wrap field email  required ">
      <label class="pure-material-textfield-outlined" for="email">
         <input class="field- input-text t-validate" type="text" name="email" id="email" data-validate="{required:true,'validate-email':true}" placeholder="" aria-required="true">
         <span>Email Id*</span>
          </label>
   </div>
   <div class="form--input-field-wrap field mobile-no  required">
      <label class="pure-material-textfield-outlined" for="mobile-no">
         <input class="field- input-text t-validate" type="text" name="mobile" id="mobile" data-validate="{required:true,'validate-digits':true}" placeholder="" aria-required="true" maxlength="10">
         <span>Contact No.*</span>
        </label>
   </div>
   <div class="form--input-field-wrap field pincode  required ">
      <label class="pure-material-textfield-outlined" for="pincode">

      <select name='pincode' class='form-control' required='true'>
        <?php foreach($pincode as $option) {
                if($option['value'] == '')
                { ?>
                    <option value="">Please select Pincode</option>
            <?php } else{ ?>
                    <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
        <?php }} ?>
        </select>

        <span>Pincode*</span>
        </label>
   </div> 

   <div class="form--input-field-wrap field bedsheetqty  required ">
      <label class="pure-material-textfield-outlined" for="bedsheetqty">
      <select name='bedsheetqty' class='form-control' required='true'>
        <?php foreach($bedsheetqty as $option) {
                if($option['value'] == '')
                { ?>
                    <option value="">Please select Quantity</option>
            <?php } else{ ?>
                    <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
        <?php }} ?>
        </select>
            <span>BedSheet Qty*</span>
        </label>
   </div> 

   <div class="form--input-field-wrap field pickup required ">
      <label class="pure-material-textfield-outlined" for="pickup">
      <select name='pickup' class='form-control' required='true'>
        <?php foreach($pickup as $option) {
                if($option['value'] == '')
                { ?>
                    <option value="">Please select Pickup</option>
            <?php } else{ ?>
                    <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
        <?php }} ?>
        </select>
        <span>Pickup Timeline*</span>
        </label>
   </div> 

    <div  class="g-recaptcha" data-sitekey="6Lfv8MwZAAAAACIMQ_gk53W2jQPg9C46hfKPLH7A">&nbsp;</div>
    <div style="display:none" id="error-msg">
                  <span><?php echo __('This is a required field.') ?></span>
             </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="base--btn primary--btn">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>

</div>
  </div>
</section>
<script>
    function checkCaptcha() {
        if ((jQuery('#g-recaptcha-response').val()) === '') {
            jQuery('#error-msg').css('display', 'block');
            jQuery('#error-msg').css('color', '#df280a');
            jQuery('#error-msg').css('font-size', 13);
            return false;
        }
        else {
            jQuery('#error-msg').css('display', 'none');
        }
    }
</script>