<div class="mybody">
<h2><?php echo 'This is my first module'; ?></h2>
<h2>Artical Data</h2>
<a class="action primary" href=<?= $block->getUrl('mymodule/index/insert'); ?>>Add Record</a>
<table>
     <tr>
          <th>Id</th>
          <th>Title</th>
          <th>Content</th>
          <th>Created At</th>
          <th>Action</th>

     </tr>
 
     <?php
          $collection = $block->getArticles();
          foreach($collection as $d){
     ?>
     <tr>
          <td><?php echo $d->getArticleId (); ?></td>
          <td><?php echo $d->getArticleSubject (); ?></td>
          <td><?php echo $d->getContent (); ?></td>
          <td><?php echo $d->getCreatedAt (); ?></td>
          <td><a class="action primary" href=<?= $block->getUrl('mymodule/index/edit')."id/".$d->getArticleId (); ?>>Edit Record</a></td>
          <td><a class="action primary" href="<?= $block->getUrl('mymodule/index/delete').'?id='.$d->getArticleId();; ?>">Delete</a>
</td>

     </tr>
     <?php } ?>
</table>
<h2><?php echo "Get Product Content" ?></h2>
</div>