<?php
/**
 * @category   Ambab
 * @package    Ambab_Exchange
 * @author     letsdevelophp@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Ambab\Exchange\Controller\Index;

use Magento\Framework\App\Action\Context;
use Ambab\Exchange\Model\ExchangeFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Exchange
     */
    protected $_exchange;

    public function __construct(
		Context $context,
        ExchangeFactory $exchange
    ) {
        $this->_exchange = $exchange;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();

        /*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $userModel = $objectManager->create('Delhivery\Lastmile\Model\Pincode');
        $userModel = $userModel->getCollection()->addFieldToFilter("pin",$data['pincode'])->getFirstItem();

        $city = $userModel->getDistrict();
        $state = $userModel->getStateCode();

        $data['state'] = $state;
        $data['city'] = $city;*/

    	$exchange = $this->_exchange->create();
        $exchange->setData($data);
        if($exchange->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('exchange-program');
        return $resultRedirect;
    }
}
