<?php
/**
 * @category   Ambab
 * @package    Ambab_Exchange
 * @author     letsdevelophp@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Ambab\Exchange\Controller\Adminhtml\Items;

class Index extends \Ambab\Exchange\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('Ambab_Exchange::test');
        $resultPage->getConfig()->getTitle()->prepend(__('Exchange Requests'));
        $resultPage->addBreadcrumb(__('Exchange'), __('Exchange'));
        $resultPage->addBreadcrumb(__('Requests'), __('Requests'));
        return $resultPage;
    }
}